export const YOUTUBE_LOGO_IMG =
  "https://wallpapers.com/images/featured/youtube-logo-background-xuljaasdgk44enmb.jpg";
export const MIC_IMAGE =
  "https://cdn-icons-png.flaticon.com/512/1082/1082810.png";
export const NOTIFICATION_ICON =
  "https://cdn-icons-png.flaticon.com/512/3119/3119338.png";
export const USER_PNG =
  "https://w7.pngwing.com/pngs/178/595/png-transparent-user-profile-computer-icons-login-user-avatars-thumbnail.png";

//Youtube cred
export const YOUTUBE_API_KEY = "AIzaSyCT9TOryY9pm4G2-yPLrF1VxuQG0E_aOmY";

export const YOUTUBE_CATEGORY_LIST = [
  "All",
  "Gaming",
  "ESports",
  "Live",
  "Music",
  "News",
  "Roast",
  "Reaction",
  "Sports",
  "Comedy",
  "Education",
  "Marvel",
  "Film & Animation",
  "SuperHero",
  "Board Games",
  "JukeBox",
  "Software Engineering",
];

export const YOUTUBE_MOST_POPULAR_API = `https://youtube.googleapis.com/youtube/v3/videos?part=snippet%2CcontentDetails%2Cstatistics&chart=mostPopular&maxResults=200&regionCode=IN&key=${YOUTUBE_API_KEY}`;

export const YOUTUBE_COMMENT_API = `https://youtube.googleapis.com/youtube/v3/comments?part=snippet&parentId=UgzDE2tasfmrYLyNkGt4AaABAg&maxResults=50&key=${YOUTUBE_API_KEY}&textFormat=plainText`;

export const YOUTUBE_SEARCH_SUGGESTION =
  "http://suggestqueries.google.com/complete/search?client=firefox&ds=yt&q=";

export const nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export const YOUTUBE_SEARCH_RESULTS_API =
  "https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=50&";

export const quotes = [
  "The only way to do great work is to love what you do. - Steve Jobs",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
  "Believe you can and you're halfway there. - Theodore Roosevelt",
  "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
  "You miss 100% of the shots you don’t take. - Wayne Gretzky",
  "Act as if what you do makes a difference. It does. - William James",
  "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
  "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
  "The purpose of our lives is to be happy. - Dalai Lama",
  "Life is what happens when you're busy making other plans. - John Lennon",
  "Get busy living or get busy dying. - Stephen King",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
  "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
  "The best way to predict your future is to create it. - Abraham Lincoln",
  "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
  "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
  "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
  "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
  "Keep going. Be all in. - Bryan Hutchinson",
  "The best way out is always through. - Robert Frost",
  "You can do anything you set your mind to. - Benjamin Franklin",
  "Don’t let yesterday take up too much of today. - Will Rogers",
  "The secret of getting ahead is getting started. - Mark Twain",
  "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
  "Dream big and dare to fail. - Norman Vaughan",
  "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
  "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
  "If you can dream it, you can achieve it. - Zig Ziglar",
  "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
  "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
  "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
  "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
  "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don’t quit. - Conrad Hilton",
  "If you really want to do something, you'll find a way. If you don't, you'll find an excuse. - Jim Rohn",
  "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
  "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
  "It is never too late to be what you might have been. - George Eliot",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
  "The best revenge is massive success. - Frank Sinatra",
  "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
  "Do one thing every day that scares you. - Eleanor Roosevelt",
  "What we achieve inwardly will change outer reality. - Plutarch",
  "All our dreams can come true if we have the courage to pursue them. - Walt Disney",
  "It does not matter how slowly you go as long as you do not stop. - Confucius",
  "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
  "Everything you’ve ever wanted is on the other side of fear. - George Addair",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
  "We may encounter many defeats but we must not be defeated. - Maya Angelou",
  "Whether you think you can or think you can’t, you’re right. - Henry Ford",
  "Change your thoughts and you change your world. - Norman Vincent Peale",
  "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
  "If opportunity doesn’t knock, build a door. - Milton Berle",
  "Do not be embarrassed by your failures, learn from them and start again. - Richard Branson",
  "It always seems impossible until it’s done. - Nelson Mandela",
  "The best way to get started is to quit talking and begin doing. - Walt Disney",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
  "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak. - Thomas Carlyle",
  "Strength does not come from physical capacity. It comes from an indomitable will. - Mahatma Gandhi",
  "Don't limit your challenges. Challenge your limits. - Unknown",
  "Great things never came from comfort zones. - Neil Strauss",
  "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
  "The only way to do great work is to love what you do. If you haven’t found it yet, keep looking. Don’t settle. - Steve Jobs",
  "Your life only gets better when you get better. - Brian Tracy",
  "You are not a drop in the ocean. You are the entire ocean in a drop. - Rumi",
  "Don't wish it were easier. Wish you were better. - Jim Rohn",
  "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible. - Francis of Assisi",
  "It's not about ideas. It's about making ideas happen. - Scott Belsky",
  "You can't build a reputation on what you are going to do. - Henry Ford",
  "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
  "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
  "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
  "Too many of us are not living our dreams because we are living our fears. - Les Brown",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
  "Don’t judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
  "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
  "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
  "It is our choices that show what we truly are, far more than our abilities. - J.K. Rowling",
  "What you do speaks so loudly that I cannot hear what you say. - Ralph Waldo Emerson",
  "Success is not in what you have, but who you are. - Bo Bennett",
  "A man is but the product of his thoughts. What he thinks, he becomes. - Mahatma Gandhi",
  "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
  "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
  "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
  "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
  "The way to get started is to quit talking and begin",
];

export const YOUTUBE_CATEGORY_API = `https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&videoCategoryId=10&maxResults=200&key=${YOUTUBE_API_KEY}&q=`;

export const OFFSET = 10;
